// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruvodce.server.Data;

#nullable disable

namespace pruvodce.server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522202733_AddEventPoints")]
    partial class AddEventPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PointTeacher", b =>
                {
                    b.Property<string>("PointsPointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeachersTeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointsPointId", "TeachersTeacherId");

                    b.HasIndex("TeachersTeacherId");

                    b.ToTable("PointTeacher");
                });

            modelBuilder.Entity("pruvodce.server.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("Name", "StartDate")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("pruvodce.server.Models.EventBuilding", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "BuildingId");

                    b.ToTable("EventBuildings");
                });

            modelBuilder.Entity("pruvodce.server.Models.EventPoint", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "PointId");

                    b.HasIndex("PointId");

                    b.ToTable("EventPoints");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AreStudents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Icon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecializationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PointId");

                    b.HasIndex("NoteId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("pruvodce.server.Models.PointSubject", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("PointSubjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.Property<string>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("pruvodce.server.Models.StudentNote", b =>
                {
                    b.Property<string>("StudentNoteId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNoteId");

                    b.ToTable("StudentNote");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("NoteId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeacherId");

                    b.HasIndex("NoteId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("PointTeacher", b =>
                {
                    b.HasOne("pruvodce.server.Models.Point", null)
                        .WithMany()
                        .HasForeignKey("PointsPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pruvodce.server.Models.EventBuilding", b =>
                {
                    b.HasOne("pruvodce.server.Models.Event", "Event")
                        .WithMany("EventBuildings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("pruvodce.server.Models.EventPoint", b =>
                {
                    b.HasOne("pruvodce.server.Models.Event", "Event")
                        .WithMany("EventPoints")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Point", "Point")
                        .WithMany("EventPoints")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.HasOne("pruvodce.server.Models.StudentNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.HasOne("pruvodce.server.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Specialization", "Specialization")
                        .WithMany("Points")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Room");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("pruvodce.server.Models.PointSubject", b =>
                {
                    b.HasOne("pruvodce.server.Models.Point", "Point")
                        .WithMany("PointSubjects")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Subject", "Subject")
                        .WithMany("PointSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.HasOne("pruvodce.server.Models.StudentNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("pruvodce.server.Models.Teacher", b =>
                {
                    b.HasOne("pruvodce.server.Models.StudentNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Navigation("EventBuildings");

                    b.Navigation("EventPoints");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.Navigation("EventPoints");

                    b.Navigation("PointSubjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.Navigation("PointSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
