// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruvodce.server.Data;

#nullable disable

namespace pruvodce.server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429100405_ups")]
    partial class ups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PointSubject", b =>
                {
                    b.Property<string>("PointsPointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectsSubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointsPointId", "SubjectsSubjectId");

                    b.HasIndex("SubjectsSubjectId");

                    b.ToTable("PointSubject");
                });

            modelBuilder.Entity("PointTeacher", b =>
                {
                    b.Property<string>("PointsPointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeachersTeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointsPointId", "TeachersTeacherId");

                    b.HasIndex("TeachersTeacherId");

                    b.ToTable("PointTeacher");
                });

            modelBuilder.Entity("pruvodce.server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("pruvodce.server.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointId");

                    b.HasIndex("EventId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("pruvodce.server.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.Property<string>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Icon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("PointSubject", b =>
                {
                    b.HasOne("pruvodce.server.Models.Point", null)
                        .WithMany()
                        .HasForeignKey("PointsPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointTeacher", b =>
                {
                    b.HasOne("pruvodce.server.Models.Point", null)
                        .WithMany()
                        .HasForeignKey("PointsPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.HasOne("pruvodce.server.Models.Event", "Event")
                        .WithMany("Points")
                        .HasForeignKey("EventId");

                    b.HasOne("pruvodce.server.Models.Specialization", "Specialization")
                        .WithMany("Points")
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Event");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
