// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruvodce.server.Data;

#nullable disable

namespace pruvodce.server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("pruvodce.server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Address = "Školní 1",
                            Name = "Hlavní budova"
                        });
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EndDate = new DateTime(2026, 4, 17, 0, 30, 15, 677, DateTimeKind.Local).AddTicks(3171),
                            IsActive = true,
                            Name = "DOD 2026 Leden",
                            StartDate = new DateTime(2026, 4, 16, 0, 30, 15, 675, DateTimeKind.Local).AddTicks(7536)
                        });
                });

            modelBuilder.Entity("pruvodce.server.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgOutline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FloorId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            FloorId = 1,
                            BuildingId = 1,
                            Name = "Přízemí",
                            SvgOutline = "M 0 0 L 100 100"
                        });
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LabelX")
                        .HasColumnType("REAL");

                    b.Property<double>("LabelY")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("PointId");

                    b.HasIndex("EventId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            PointId = "P1",
                            EventId = 1,
                            Label = "Stanoviště robotiky",
                            LabelX = 50.0,
                            LabelY = 50.0,
                            RoomId = "A214"
                        });
                });

            modelBuilder.Entity("pruvodce.server.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("LabelX")
                        .HasColumnType("REAL");

                    b.Property<double?>("LabelY")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = "A214",
                            FloorId = 1,
                            Label = "Laboratoř IT",
                            SvgData = "...",
                            Type = 1
                        });
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.Property<string>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecializationId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.HasIndex("PointId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("pruvodce.server.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("pruvodce.server.Models.Floor", b =>
                {
                    b.HasOne("pruvodce.server.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.HasOne("pruvodce.server.Models.Event", "Event")
                        .WithMany("Points")
                        .HasForeignKey("EventId");

                    b.HasOne("pruvodce.server.Models.Room", "Room")
                        .WithMany("Points")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruvodce.server.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Event");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("pruvodce.server.Models.Room", b =>
                {
                    b.HasOne("pruvodce.server.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("pruvodce.server.Models.Specialization", b =>
                {
                    b.HasOne("pruvodce.server.Models.Subject", null)
                        .WithMany("Specialization")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.HasOne("pruvodce.server.Models.Point", null)
                        .WithMany("Subjects")
                        .HasForeignKey("PointId");

                    b.HasOne("pruvodce.server.Models.Room", "Room")
                        .WithMany("Subjects")
                        .HasForeignKey("RoomId");

                    b.HasOne("pruvodce.server.Models.Teacher", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("pruvodce.server.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("pruvodce.server.Models.Event", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("pruvodce.server.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("pruvodce.server.Models.Point", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Room", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("pruvodce.server.Models.Subject", b =>
                {
                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("pruvodce.server.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
